In [85]:
import numpy as np
import pandas as pd

In [86]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### Pandas

* Скачайте любой табличный датасет (можете использовать тот же, что и в дз к занятию "Знакомство с библиотеками"), например, с https://www.kaggle.com/datasets
* Проведите поноценный EDA 
    * "погрузитесь" в данные
    * составьте описание измерений из датасета
    * очистите данные, если это необходимо
    * попробуйте создать дополнительные переменные, которые могут помочь лучше понять данные

#### Загрузка и обзор данных

https://www.kaggle.com/datasets/slavapasedko/belarus-used-cars-prices

In [87]:
# загрузка датасета
df = pd.read_csv('/content/drive/MyDrive/cars.csv')
df.head()

make model  priceUSD  year     condition  mileage(kilometers) fuel_type  \
0  mazda     2      5500  2008  with mileage             162000.0    petrol   
1  mazda     2      5350  2009  with mileage             120000.0    petrol   
2  mazda     2      7000  2009  with mileage              61000.0    petrol   
3  mazda     2      3300  2003  with mileage             265000.0    diesel   
4  mazda     2      5200  2008  with mileage              97183.0    diesel   

   volume(cm3)     color transmission         drive_unit segment  
0       1500.0  burgundy    mechanics  front-wheel drive       B  
1       1300.0     black    mechanics  front-wheel drive       B  
2       1500.0    silver         auto  front-wheel drive       B  
3       1400.0     white    mechanics  front-wheel drive       B  
4       1400.0      gray    mechanics  front-wheel drive       B

In [88]:
df.rename(columns={'make': 'manufacture', 'priceUSD': 'price(USD)'}, inplace=True)

In [89]:
# описание датасета
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56244 entries, 0 to 56243
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   manufacture          56244 non-null  object 
 1   model                56244 non-null  object 
 2   price(USD)           56244 non-null  int64  
 3   year                 56244 non-null  int64  
 4   condition            56244 non-null  object 
 5   mileage(kilometers)  56244 non-null  float64
 6   fuel_type            56244 non-null  object 
 7   volume(cm3)          56197 non-null  float64
 8   color                56244 non-null  object 
 9   transmission         56244 non-null  object 
 10  drive_unit           54339 non-null  object 
 11  segment              50953 non-null  object 
dtypes: float64(2), int64(2), object(8)
memory usage: 5.1+ MB


#### Заполнение пропусков

In [90]:
# проверка на наличие пропусков
df.isnull().sum()

manufacture               0
model                     0
price(USD)                0
year                      0
condition                 0
mileage(kilometers)       0
fuel_type                 0
volume(cm3)              47
color                     0
transmission              0
drive_unit             1905
segment                5291
dtype: int64

volume(cm3)

In [91]:
df['volume(cm3)'].value_counts()

2000.0    10742
1600.0     8646
1800.0     5983
1900.0     3651
2500.0     3395
          ...  
1992.0        1
1797.0        1
2308.0        1
1464.0        1
1970.0        1
Name: volume(cm3), Length: 458, dtype: int64

In [92]:
# заполним пропуски в volume(cm3) средним значением
df['volume(cm3)'].fillna(df['volume(cm3)'].mean(), inplace = True)

drive_unit

In [93]:
df['drive_unit'].value_counts()

front-wheel drive             38016
rear drive                     6836
all-wheel drive                5890
part-time four-wheel drive     3597
Name: drive_unit, dtype: int64

In [94]:
# заполним пропуски в drive_unit самым частым значением
df['drive_unit'].fillna('front-wheel drive', inplace=True)

segment

In [95]:
df['segment'].value_counts()

D    12605
C    10617
J     8629
M     6313
E     6274
B     4393
F      896
S      765
A      461
Name: segment, dtype: int64

In [96]:
# заполним пропуски в segment самым частым значением
df['segment'].fillna('D', inplace=True)

In [97]:
df.isnull().sum()

manufacture            0
model                  0
price(USD)             0
year                   0
condition              0
mileage(kilometers)    0
fuel_type              0
volume(cm3)            0
color                  0
transmission           0
drive_unit             0
segment                0
dtype: int64

#### Числовые признаки

In [98]:
# вывод статистик по числовым признакам
df.describe()

price(USD)          year  mileage(kilometers)   volume(cm3)
count   56244.000000  56244.000000         5.624400e+04  56244.000000
mean     7415.456440   2003.454840         2.443956e+05   2104.860615
std      8316.959261      8.144247         3.210307e+05    958.800766
min        48.000000   1910.000000         0.000000e+00    500.000000
25%      2350.000000   1998.000000         1.370000e+05   1600.000000
50%      5350.000000   2004.000000         2.285000e+05   1997.000000
75%      9807.500000   2010.000000         3.100000e+05   2300.000000
max    235235.000000   2019.000000         9.999999e+06  20000.000000

In [99]:
# корреляция признаков
df.corr()

price(USD)      year  mileage(kilometers)  volume(cm3)
price(USD)             1.000000  0.605131            -0.170933     0.264116
year                   0.605131  1.000000            -0.233049     0.027349
mileage(kilometers)   -0.170933 -0.233049             1.000000     0.013450
volume(cm3)            0.264116  0.027349             0.013450     1.000000

#### Группировка данных

In [100]:
# добавление столбца id
df['id'] = df.index
df.head()

manufacture model  price(USD)  year     condition  mileage(kilometers)  \
0       mazda     2        5500  2008  with mileage             162000.0   
1       mazda     2        5350  2009  with mileage             120000.0   
2       mazda     2        7000  2009  with mileage              61000.0   
3       mazda     2        3300  2003  with mileage             265000.0   
4       mazda     2        5200  2008  with mileage              97183.0   

  fuel_type  volume(cm3)     color transmission         drive_unit segment  id  
0    petrol       1500.0  burgundy    mechanics  front-wheel drive       B   0  
1    petrol       1300.0     black    mechanics  front-wheel drive       B   1  
2    petrol       1500.0    silver         auto  front-wheel drive       B   2  
3    diesel       1400.0     white    mechanics  front-wheel drive       B   3  
4    diesel       1400.0      gray    mechanics  front-wheel drive       B   4

In [101]:
# количество автомобилей с определённым состоянием
df.groupby(['condition'])['id'].count().sort_values(ascending=False)

condition
with mileage    55278
with damage       512
for parts         454
Name: id, dtype: int64

In [102]:
# общая стоимость автомобилей по годам
df.groupby(['year'])['price(USD)'].sum()

year
1910          48
1933       50000
1936        4991
1938       12500
1942       17000
          ...   
2015    34360734
2016    25811333
2017    14398430
2018    14049194
2019     7530816
Name: price(USD), Length: 78, dtype: int64

In [103]:
# количество автомобилей по цветам
df.groupby(['color'])['id'].count().sort_values(ascending=False)

color
black       12385
silver      10075
blue         8083
gray         5807
white        5292
green        3911
other        3397
red          2744
burgundy     2026
brown        1349
purple        625
yellow        317
orange        233
Name: id, dtype: int64

In [104]:
# средний пробег автомобилей по годам
df.groupby(['year'])['mileage(kilometers)'].mean()

year
1910     25000.000000
1933         1.000000
1936    175000.000000
1938    100000.000000
1942     40000.000000
            ...      
2015    116479.730911
2016    104386.793542
2017     56678.885681
2018     29489.473712
2019      7164.508482
Name: mileage(kilometers), Length: 78, dtype: float64

In [105]:
# средний объём по годам
df.groupby(['year'])['volume(cm3)'].mean()

year
1910    1100.000000
1933    2400.000000
1936    1800.000000
1938    3000.000000
1942    2000.000000
           ...     
2015    1861.145241
2016    1808.975711
2017    1934.270584
2018    1955.915300
2019    2063.342505
Name: volume(cm3), Length: 78, dtype: float64

In [106]:
# количество автмобилей по виду топлива
df.groupby(['fuel_type'])['id'].count().sort_values(ascending=False)

fuel_type
petrol        36405
diesel        19792
electrocar       47
Name: id, dtype: int64

In [108]:
# количество автомобилей определённого производителя
df.groupby(['manufacture'])['id'].count().sort_values(ascending=False)

manufacture
volkswagen        6861
audi              4030
bmw               4013
opel              3779
renault           3713
                  ... 
mclaren              1
roewe                1
jac                  1
dong-feng            1
shanghai-maple       1
Name: id, Length: 96, dtype: int64

In [109]:
# количество автомобилей по типу коробки передач
df.groupby(['transmission'])['id'].count().sort_values(ascending=False)

transmission
mechanics    36056
auto         20188
Name: id, dtype: int64

#### Добавление столбцов

In [110]:
# возраст автомобиля
current_year = 2022
df['age'] = current_year - df['year']
df.head()

manufacture model  price(USD)  year     condition  mileage(kilometers)  \
0       mazda     2        5500  2008  with mileage             162000.0   
1       mazda     2        5350  2009  with mileage             120000.0   
2       mazda     2        7000  2009  with mileage              61000.0   
3       mazda     2        3300  2003  with mileage             265000.0   
4       mazda     2        5200  2008  with mileage              97183.0   

  fuel_type  volume(cm3)     color transmission         drive_unit segment  \
0    petrol       1500.0  burgundy    mechanics  front-wheel drive       B   
1    petrol       1300.0     black    mechanics  front-wheel drive       B   
2    petrol       1500.0    silver         auto  front-wheel drive       B   
3    diesel       1400.0     white    mechanics  front-wheel drive       B   
4    diesel       1400.0      gray    mechanics  front-wheel drive       B   

   id  age  
0   0   14  
1   1   13  
2   2   13  
3   3   19  
4   4   14

In [111]:
# процент от максимальной цены
df['price_percentage'] = (df['price(USD)'] / max(df['price(USD)'])) * 100
df.head()

manufacture model  price(USD)  year     condition  mileage(kilometers)  \
0       mazda     2        5500  2008  with mileage             162000.0   
1       mazda     2        5350  2009  with mileage             120000.0   
2       mazda     2        7000  2009  with mileage              61000.0   
3       mazda     2        3300  2003  with mileage             265000.0   
4       mazda     2        5200  2008  with mileage              97183.0   

  fuel_type  volume(cm3)     color transmission         drive_unit segment  \
0    petrol       1500.0  burgundy    mechanics  front-wheel drive       B   
1    petrol       1300.0     black    mechanics  front-wheel drive       B   
2    petrol       1500.0    silver         auto  front-wheel drive       B   
3    diesel       1400.0     white    mechanics  front-wheel drive       B   
4    diesel       1400.0      gray    mechanics  front-wheel drive       B   

   id  age  price_percentage  
0   0   14          2.338087  
1   1   13          2.274321  
2   2   13          2.975748  
3   3   19          1.402852  
4   4   14          2.210555

In [112]:
# процент от максимального пробега
df['mileage_procent'] = (df['mileage(kilometers)'] / max(df['mileage(kilometers)'])) * 100
df.head()

manufacture model  price(USD)  year     condition  mileage(kilometers)  \
0       mazda     2        5500  2008  with mileage             162000.0   
1       mazda     2        5350  2009  with mileage             120000.0   
2       mazda     2        7000  2009  with mileage              61000.0   
3       mazda     2        3300  2003  with mileage             265000.0   
4       mazda     2        5200  2008  with mileage              97183.0   

  fuel_type  volume(cm3)     color transmission         drive_unit segment  \
0    petrol       1500.0  burgundy    mechanics  front-wheel drive       B   
1    petrol       1300.0     black    mechanics  front-wheel drive       B   
2    petrol       1500.0    silver         auto  front-wheel drive       B   
3    diesel       1400.0     white    mechanics  front-wheel drive       B   
4    diesel       1400.0      gray    mechanics  front-wheel drive       B   

   id  age  price_percentage  mileage_procent  
0   0   14          2.338087          1.62000  
1   1   13          2.274321          1.20000  
2   2   13          2.975748          0.61000  
3   3   19          1.402852          2.65000  
4   4   14          2.210555          0.97183

### Numpy

1. Вычислите A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [124]:
A = np.array([[1, -2, 4], [2, 0, -1]])
B = np.array([[5, 2, 3], [4, 6, 2]])

In [125]:
A + B

array([[6, 0, 7],
       [6, 6, 1]])

In [126]:
A - B

array([[-4, -4,  1],
       [-2, -6, -3]])

2. Найдите матрицу С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [127]:
A = np.array([
    [1, 2],
    [2, -1],
    [3, 0]
    ])

B = np.array([
    [-1, 1],
    [1, 2],
    [0, 0]
    ])

In [128]:
C = A - 3 * B
C

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

3. Вычислите С = AB
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [129]:
A = np.array([
    [1, -1],
    [2, 0],
    [3, 0]
])

B = np.array([
   [1, 1],
   [2, 0] 
])

In [130]:
C = A@B
C

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

4. Вычислите определитель матрицы А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [131]:
A = np.array([
    [6, -1, 4],
    [2, 1, 10],
    [8, 0, 2]
])

np.linalg.det(A)

-95.99999999999999

5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [132]:
A = np.array([
    [3, 3, -1],
    [4, 1, 3],
    [1, -2, -2]
])
B = np.linalg.inv(A)
B

array([[ 0.07407407,  0.14814815,  0.18518519],
       [ 0.2037037 , -0.09259259, -0.24074074],
       [-0.16666667,  0.16666667, -0.16666667]])

In [133]:
A @ B

array([[ 1.00000000e+00, -2.77555756e-17,  1.38777878e-16],
       [ 2.77555756e-17,  1.00000000e+00,  2.77555756e-17],
       [-5.55111512e-17,  5.55111512e-17,  1.00000000e+00]])

In [134]:
B @ A

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.55111512e-17,  1.00000000e+00, -1.11022302e-16],
       [-2.77555756e-17, -5.55111512e-17,  1.00000000e+00]])