# Импорт библиотек

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

<img src='https://drive.google.com/uc?export=view&id=1q1pSMnZVVhVeE9l2zGckBCF33BS2vKBd'>

# Загрузка данных

In [2]:
!wget 'https://drive.google.com/uc?id=1oRtvvrVUoep5nnSexngfNFEB4cin5Rsa' -O final.csv

--2022-09-20 13:08:26--  https://drive.google.com/uc?id=1oRtvvrVUoep5nnSexngfNFEB4cin5Rsa
Resolving drive.google.com (drive.google.com)... 142.251.45.14, 2607:f8b0:4004:83e::200e
Connecting to drive.google.com (drive.google.com)|142.251.45.14|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0s-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/6i1c4g0fbu71gtol6p2fgdskllqlkm0d/1663679250000/14904333240138417226/*/1oRtvvrVUoep5nnSexngfNFEB4cin5Rsa?uuid=ee8f707f-9ae5-424b-a993-446abb07ec5b [following]
--2022-09-20 13:08:29--  https://doc-0s-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/6i1c4g0fbu71gtol6p2fgdskllqlkm0d/1663679250000/14904333240138417226/*/1oRtvvrVUoep5nnSexngfNFEB4cin5Rsa?uuid=ee8f707f-9ae5-424b-a993-446abb07ec5b
Resolving doc-0s-c0-docs.googleusercontent.com (doc-0s-c0-docs.googleusercontent.com)... 172.253.115.132, 2607:f8b0:4004:c06::84
Connecting to doc-0s-c0-docs.goo

In [3]:
df = pd.read_csv('/content/final.csv')

In [4]:
df

store  dayofweek        date  sales  customers  open  promo  \
0            1          3  2018-01-01   5530        668     1      0   
1            2          3  2018-01-01   4422        650     1      0   
2            3          3  2018-01-01   6823        805     1      0   
3            4          3  2018-01-01   9941       1429     1      0   
4            5          3  2018-01-01   4253        577     1      0   
...        ...        ...         ...    ...        ...   ...    ...   
1016090   1111          5  2020-07-29   5723        422     1      1   
1016091   1112          5  2020-07-29   9626        767     1      1   
1016092   1113          5  2020-07-29   7289        720     1      1   
1016093   1114          5  2020-07-29  27508       3745     1      1   
1016094   1115          5  2020-07-29   8680        538     1      1   

               lat        lon  
0        55.682829  37.416212  
1        55.686410  37.415503  
2        55.885081  37.476452  
3        55.711356  37.389027  
4        55.902867  37.609132  
...            ...        ...  
1016090  55.878577  37.706292  
1016091  55.791374  37.823187  
1016092  55.756921  37.824353  
1016093  55.798922  37.822139  
1016094  55.582867  37.653329  

[1016095 rows x 9 columns]

- store - магазин
- dayofweek - день недели
- date - дата
- sales - продажи
- customers - клиенты
- open - открыт магазин или нет
- promo - была ли промо акция
- lat - широта
- lon - долгота

# Делаем прогноз на июль 2020 года

<img src='https://drive.google.com/uc?export=view&id=1lkMiS2f-f-DwrBkEQIEp3HBxKm2Im9zX'>

In [5]:
df_train = df[df['date'] < '2020-07-01']
df_test = df[df['date'] >= '2020-07-01']

In [6]:
df_train

store  dayofweek        date  sales  customers  open  promo  \
0           1          3  2018-01-01   5530        668     1      0   
1           2          3  2018-01-01   4422        650     1      0   
2           3          3  2018-01-01   6823        805     1      0   
3           4          3  2018-01-01   9941       1429     1      0   
4           5          3  2018-01-01   4253        577     1      0   
...       ...        ...         ...    ...        ...   ...    ...   
983755   1111          4  2020-06-30   3945        329     1      1   
983756   1112          4  2020-06-30   7447        577     1      1   
983757   1113          4  2020-06-30   7932        793     1      1   
983758   1114          4  2020-06-30  24898       3784     1      1   
983759   1115          4  2020-06-30   6858        452     1      1   

              lat        lon  
0       55.682829  37.416212  
1       55.686410  37.415503  
2       55.885081  37.476452  
3       55.711356  37.389027  
4       55.902867  37.609132  
...           ...        ...  
983755  55.878577  37.706292  
983756  55.791374  37.823187  
983757  55.756921  37.824353  
983758  55.798922  37.822139  
983759  55.582867  37.653329  

[983760 rows x 9 columns]

In [7]:
df_test

store  dayofweek        date  sales  customers  open  promo  \
983760       1          5  2020-07-01   4665        538     1      1   
983761       2          5  2020-07-01   4838       1029     1      1   
983762       3          5  2020-07-01   8149        742     1      1   
983763       4          5  2020-07-01  11543       1395     1      1   
983764       5          5  2020-07-01   4475        527     1      1   
...        ...        ...         ...    ...        ...   ...    ...   
1016090   1111          5  2020-07-29   5723        422     1      1   
1016091   1112          5  2020-07-29   9626        767     1      1   
1016092   1113          5  2020-07-29   7289        720     1      1   
1016093   1114          5  2020-07-29  27508       3745     1      1   
1016094   1115          5  2020-07-29   8680        538     1      1   

               lat        lon  
983760   55.682829  37.416212  
983761   55.686410  37.415503  
983762   55.885081  37.476452  
983763   55.711356  37.389027  
983764   55.902867  37.609132  
...            ...        ...  
1016090  55.878577  37.706292  
1016091  55.791374  37.823187  
1016092  55.756921  37.824353  
1016093  55.798922  37.822139  
1016094  55.582867  37.653329  

[32335 rows x 9 columns]

# Возьмём несколько признаков

In [8]:
features = [
    'store',
    'dayofweek',
    'customers',
    'open',
    'promo',
]

target = ['sales']

In [9]:
X_train = df_train[features]
y_train = df_train[target]

X_test = df_test[features]
y_test = df_test[target]

In [10]:
X_train

store  dayofweek  customers  open  promo
0           1          3        668     1      0
1           2          3        650     1      0
2           3          3        805     1      0
3           4          3       1429     1      0
4           5          3        577     1      0
...       ...        ...        ...   ...    ...
983755   1111          4        329     1      1
983756   1112          4        577     1      1
983757   1113          4        793     1      1
983758   1114          4       3784     1      1
983759   1115          4        452     1      1

[983760 rows x 5 columns]

In [11]:
y_train

sales
0        5530
1        4422
2        6823
3        9941
4        4253
...       ...
983755   3945
983756   7447
983757   7932
983758  24898
983759   6858

[983760 rows x 1 columns]

# Воспользуемся простым методом прогноза

<img src='https://drive.google.com/uc?export=view&id=1alUGHx-Pabz3C3xvFDHxYbgP3tsPsH1D'>

In [12]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

# Научим нашу модель

In [13]:
model.fit(
    X_train,
    y_train
)

LinearRegression()

In [14]:
coefs = model.coef_[0]
coefs

array([-1.51031308e-01, -5.55572871e+01,  6.07463705e+00,  1.67556349e+03,
        1.27110167e+03])

In [15]:
intercept = model.intercept_
intercept

array([352.11911259])

In [16]:
df_train[features].head(1)

store  dayofweek  customers  open  promo
0      1          3        668     1      0

In [17]:
1 * coefs[0] + 3 * coefs[1] + 668 * coefs[2] + 1 * coefs[3] + 0 * coefs[4] + intercept

array([5918.71726263])

In [18]:
model.predict(X_train.head(1))

array([[5918.71726263]])

In [19]:
X_train.head(1)

store  dayofweek  customers  open  promo
0      1          3        668     1      0

In [20]:
pred_train = model.predict(X_train)
pred_train

array([[ 5918.71726263],
       [ 5809.22276437],
       [ 6750.64047619],
       ...,
       [ 7725.64445989],
       [25894.73285244],
       [ 5653.89116239]])

In [21]:
train_preds = pd.DataFrame(pred_train, columns=['pred'])
train_preds['sales'] = y_train

train_preds

pred  sales
0        5918.717263   5530
1        5809.222764   4422
2        6750.640476   6823
3       10541.062966   9941
4        5365.321166   4253
...              ...    ...
983755   4907.314930   3945
983756   6413.673888   7447
983757   7725.644460   7932
983758  25894.732852  24898
983759   5653.891162   6858

[983760 rows x 2 columns]

# Сделаем прогноз

<img src='https://drive.google.com/uc?export=view&id=1YUyJxrl9ZLCGCJjSK1PvAm8IeHZU7brE'>

In [22]:
pred_test = model.predict(
    X_test
)

In [23]:
pred_test

array([[ 6289.00153871],
       [ 9271.49730015],
       [ 7527.9254348 ],
       ...,
       [ 7226.63866794],
       [25602.26472027],
       [ 6120.75266178]])

In [24]:
test_preds = pd.DataFrame(pred_test, columns=['pred'])
test_preds['sales'] = y_test.values

test_preds

pred  sales
0       6289.001539   4665
1       9271.497300   4838
2       7527.925435   8149
3      11494.512399  11543
4       6221.576406   4475
...             ...    ...
32330   5416.698889   5723
32331   7512.297641   9626
32332   7226.638668   7289
32333  25602.264720  27508
32334   6120.752662   8680

[32335 rows x 2 columns]

# Оценим точность прогноза

<img src='https://drive.google.com/uc?export=view&id=1LK0jRvKpxNar4OCCJI_XdqnYs8hxnIUU'>

$$1 - \frac{MSE}{var}$$

In [25]:
from sklearn.metrics import mean_squared_error, r2_score

print(f"Средняя квадратичная ошибка (MSE) модели на обучающей выборке {mean_squared_error(y_train, pred_train)}")
print(f"Средняя квадратичная ошибка (MSE) модели на тестовой выборке {mean_squared_error(y_test, pred_test)}")
print()
print(f"Коэффициент детерминации (R^2) модели на обучающей выборке {r2_score(y_train, pred_train)}")
print(f"Коэффициент детерминации (R^2) модели на тестовой выборке {r2_score(y_test, pred_test)}")

Средняя квадратичная ошибка (MSE) модели на обучающей выборке 2188564.092935027
Средняя квадратичная ошибка (MSE) модели на тестовой выборке 2308053.351565448

Коэффициент детерминации (R^2) модели на обучающей выборке 0.8526676817253495
Коэффициент детерминации (R^2) модели на тестовой выборке 0.8242831203993981


# Практическое задание

В sklearn есть встроенные («игрушечные») наборы данных. Возьмём для примера один из них — load_boston(), в нём содержится информация о ценах на недвижимость в Бостоне.

Посмотрим его описание

In [26]:
from sklearn.datasets import load_boston

boston_data = load_boston()
print(boston_data['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

Загрузим данные о признаках в "x", а целевые значения — в "y"

In [27]:
import pandas as pd

In [28]:
X = pd.DataFrame(boston_data.data, columns=boston_data.feature_names)
y = boston_data.target

Посмотрим основную информацию о нём

In [29]:
# Первые 5 строк
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)
X_train.index

Int64Index([ 33, 283, 418, 502, 402, 368, 201, 310, 343, 230,
            ...
            228,   8,  73, 400, 118, 486, 189, 495, 206, 355],
           dtype='int64', length=404)

In [31]:
X_train

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE      DIS   RAD    TAX  \
33    1.15172   0.0   8.14   0.0  0.538  5.701   95.0   3.7872   4.0  307.0   
283   0.01501  90.0   1.21   1.0  0.401  7.923   24.8   5.8850   1.0  198.0   
418  73.53410   0.0  18.10   0.0  0.679  5.957  100.0   1.8026  24.0  666.0   
502   0.04527   0.0  11.93   0.0  0.573  6.120   76.7   2.2875   1.0  273.0   
402   9.59571   0.0  18.10   0.0  0.693  6.404  100.0   1.6390  24.0  666.0   
..        ...   ...    ...   ...    ...    ...    ...      ...   ...    ...   
486   5.69175   0.0  18.10   0.0  0.583  6.114   79.8   3.5459  24.0  666.0   
189   0.08370  45.0   3.44   0.0  0.437  7.185   38.9   4.5667   5.0  398.0   
495   0.17899   0.0   9.69   0.0  0.585  5.670   28.8   2.7986   6.0  391.0   
206   0.22969   0.0  10.59   0.0  0.489  6.326   52.5   4.3549   4.0  277.0   
355   0.10659  80.0   1.91   0.0  0.413  5.936   19.5  10.5857   4.0  334.0   

     PTRATIO       B  LSTAT  
33      21.0  358.77  18.35  
283     13.6  395.52   3.16  
418     20.2   16.45  20.62  
502     21.0  396.90   9.08  
402     20.2  376.11  20.31  
..       ...     ...    ...  
486     20.2  392.68  14.98  
189     15.2  396.90   5.39  
495     19.2  393.29  17.60  
206     18.6  394.87  10.97  
355     22.0  376.04   5.57  

[404 rows x 13 columns]

In [32]:
y_train

array([13.1, 50. ,  8.8, 20.6, 12.1, 50. , 24.1, 16.1, 23.9, 24.3, 13.1,
       30.3, 15.2, 13.8, 26.4, 16.6, 18.9, 17.6, 18.7, 33.4, 20.7, 17.1,
       23.4, 26.5, 21.4, 21.5, 19.2, 50. , 50. , 23. , 10.5, 17.8, 10.9,
       21. , 13.8, 10.5, 22.2, 30.5, 19.4, 15.6, 20.2, 19.3, 34.6, 50. ,
       24. , 18.7, 19.8, 22.5, 13.3, 50. , 11.8, 11. , 23.7, 35.4, 15.2,
       24.4, 33.4, 31.6, 13.4, 34.9, 14.4, 35.4, 25.3, 18.3, 16.6, 13.4,
       23.6, 27.5, 22.2, 17.7, 14.3, 21.7,  8.4, 15.3, 20.3, 32. , 20. ,
       19.1, 28.7, 46. , 22.6, 23.9, 21.9, 15.6, 50. , 25. , 37.9, 21.6,
       19.3, 17.5, 22.9, 15. , 27.5, 10.2, 23.8, 23.9, 20.1, 16.5, 33.1,
       14.6, 28.4, 23.7, 12.3, 31.5, 22. , 12.5, 35.1, 14.9, 22.9, 22.9,
       19.3, 19.8, 20. , 29.6, 20.5, 29. , 20.7, 19.9, 11.9,  5. , 23.3,
       20.6, 22.9, 19.6, 14.1, 30.8, 43.1, 19.9, 13.9, 22.3, 14.3, 23.9,
       16. , 20.5, 10.2, 20.1, 12.8, 18.9, 22. , 20.4, 17.5, 13.1, 22. ,
       45.4, 18.8, 20. , 20.1, 21.4, 17.4, 21.1, 28

## Обучить модель

In [33]:
from sklearn.linear_model import LinearRegression
lin_model = LinearRegression()

In [34]:
lin_model.fit(X_train, y_train)

LinearRegression()

In [35]:
pred_train = lin_model.predict(X_train)
pred_train

array([13.82876985, 44.52852811,  3.91599095, 22.37795855, 18.23592252,
       25.52374759, 29.43974677, 18.69453347, 27.85646296, 24.64473374,
       20.53039645, 32.24809769, 19.53384497, 10.6751149 , 22.77616204,
       17.35106653, 18.54046999, 16.36847196, 21.72533915, 35.71120541,
       21.83662056, 19.76107221, 24.18285088, 25.5255809 , 20.8464168 ,
       24.53500383, 23.78138462, 40.86911314, 40.39520996, 29.63686507,
       12.619354  , 15.73341062, 18.21178776, 21.16340747, 16.66802114,
        5.97334491, 24.31645777, 30.41975812, 23.26407764, 19.39240148,
       16.09545573, 21.11256921, 34.44869686, 26.91553429, 30.23074628,
       18.03371864, 22.39969339, 29.3639849 , 13.012578  , 35.56341078,
       10.91286971, 13.56179599, 27.60611138, 31.30757803, 11.07295389,
       24.39197327, 28.74300261, 32.45909463, 15.73036294, 30.13719482,
        7.84896909, 34.49967116, 25.308736  , 20.0655545 , 15.24843367,
       12.43138278, 30.63133241, 16.39957657, 23.95719598, 20.73

In [37]:
pred_test = lin_model.predict(X_test)

In [38]:
pred_test

array([37.56311787, 32.14445143, 27.06573629,  5.67080633, 35.09982577,
        5.85803701, 27.53708506, 31.81019188, 26.35634771, 22.77208748,
       31.91183048, 21.50224061, 23.70119983, 33.3622504 , 28.51633591,
       14.39456899,  0.19284025, 18.66247155, 13.71004139, 14.13408635,
        2.03263952, 19.7280831 , 38.18657429, 24.19760058, 31.30247973,
       11.14144544, 25.03636951, 23.27970871, 22.49420127, 20.52972594,
       15.16513744,  6.92553586, 18.3557733 , 22.37179804, 28.91287973,
       19.02980786, 30.19357214,  8.74384915, 40.86691522, 34.53763591,
       20.70224878,  2.59618963, 29.99590282, 12.15704798, 27.10186397,
       30.8052437 , -6.24169079, 19.84885777, 20.92973441, 12.43523958,
       20.4949947 , 19.19231742, 23.69073157, 12.67998473, 17.14252424,
       25.04649176, 34.77758126, 15.23294903, 28.22306193, 21.08745388,
       20.39506129, 25.79476888, 14.72463673, 33.18635032, 23.17771307,
       13.11057248, 19.23154617, 24.61162961, 21.50327036, 22.00

In [39]:
train_preds = pd.DataFrame(pred_train, columns=['pred'])
train_preds['target'] = y_train
train_preds

pred  target
0    13.828770    13.1
1    44.528528    50.0
2     3.915991     8.8
3    22.377959    20.6
4    18.235923    12.1
..         ...     ...
399  20.003135    19.1
400  34.474582    34.9
401  16.691694    23.1
402  23.461779    24.4
403  16.959810    20.6

[404 rows x 2 columns]

In [41]:
test_preds = pd.DataFrame(pred_test, columns=['pred'])
test_preds['target'] = y_test
test_preds

pred  target
0    37.563118    37.6
1    32.144451    27.9
2    27.065736    22.6
3     5.670806    13.8
4    35.099826    35.2
..         ...     ...
97   21.912956    26.6
98   22.394774    22.4
99   13.193354    13.1
100  23.969911    23.0
101  21.199147    24.5

[102 rows x 2 columns]

## Оценить точность модели на обучающей выборке и тестовой

In [42]:
from sklearn.metrics import mean_squared_error, r2_score

In [73]:
model_metrics = pd.DataFrame(index = ['test', 'train'], columns=['mse', 'r2'])
model_metrics['mse'].loc['train'] = mean_squared_error(y_train, pred_train)
model_metrics['r2'].loc['train'] = r2_score(y_train, pred_train)
model_metrics['mse'].loc['test'] = mean_squared_error(y_test, pred_test)
model_metrics['r2'].loc['test'] = r2_score(y_test, pred_test)

In [74]:
model_metrics

mse        r2
test   20.869292  0.733449
train   22.47709  0.738339

# Дополнительные материалы:

1. Какие задачи бывают в машинном обучении https://youtu.be/ku2oPMPht2I
2. Какие бывают этапы в машинном обучении https://youtu.be/LXc6gjip_oM
3. Метрики R2, MAE, MSE - https://youtu.be/vh2smjQyhp8